####Ejemplos con numpy
###Estos son los ejercicios resueltos del taller del Bootcamp

In [ ]:
#importar librería numpy
import numpy as np


In [ ]:
print(np.__version__)


1.26.4


####Creación de ndarrays

In [ ]:
#creación de lista de números
numeros = [1,2,3,4,5,6]

numeros

[1, 2, 3, 4, 5, 6]

In [ ]:
#creación de un ndarray a partir de la lista

ndarray_numeros = np.array (numeros)

print (ndarray_numeros)

#Salida: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [ ]:
#especificación dimensiones y valores
#Creación de un ndarray de 2X3 con ceros
matriz_ceros = np.zeros((2, 3))
matriz_ceros



array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Creación de un ndarray de 3X3 con unos
matriz_unos = np.ones((3, 3))

matriz_unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Creación de un ndarray de con valores específicos
matriz_personalizado = np.array([[1,2,3],[4,5,6],[7,8,9]])

matriz_personalizado

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

####FUNCIONES DE NUMPY np.arange(inicio, fin, paso) Crea un ndarray con un rango de valores.
####Parámetros: inicio: Valor inicial (incluido). fin: valor final (excluido). paso: diferencia entre valores consecutivos.
     
     

In [ ]:
#Creación de un ndarray con valores del  0 al 9 sin incluir el 10
numeros_1 = np.arange(0, 10)

numeros_1



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Creación de un ndarray con valores del  0 al 9 de dos en dos
numeros_2 = np.arange(0, 10,2)
numeros_2


array([0, 2, 4, 6, 8])

In [ ]:
#Creación de un ndarray con valores del  0 al 4 de 0,5 en 0,5
numeros_3 = np.arange(0, 5,0.5)
print(numeros_3)



[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


####np.linspace(inicio, Crea un ndarray con valores espaciados uniformemente. Parámetros: inicio: Valor inicial (incluido)
####Parámetros. fin: Valor final (incluido). num_puntos: Número de puntos en el ndarray.


In [ ]:
#Creación de un ndarray con 10 valores espaciados
puntos_1 = np.linspace(0, 1,10)
print(puntos_1)



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#Creación de un ndarray con 5 valores espaciados uniformemente entre 2 y 10
puntos_2 = np.linspace(2, 10,5)
print(puntos_2)



[ 2.  4.  6.  8. 10.]


#### np.random.rand(dimensiones):Crea un ndarray con números aleatorios entre 0 y 1.
#### Paámetros: dimensiones: Tupla que indica la forma del ndarray

In [ ]:
#Creación de un ndarray de 3X3 con números aleatorios entre 0 y 1
matriz_aleatoria_1 = np.random.rand(3,3)
print(matriz_aleatoria_1)



[[0.93270404 0.26825483 0.16370047]
 [0.20743182 0.49837403 0.79115645]
 [0.12568976 0.43066633 0.81646772]]


In [ ]:
#Creación de un ndarray de 5 elementos con números aleatorios entre 0 y 1
vector_aleatorio_1 = np.random.rand(5)
print(vector_aleatorio_1)

[0.32303592 0.84401197 0.91111661 0.73848779 0.3084335 ]


##Características básicas de un ndarray en NumPy:
#### Dimensiones: Número de subíndices necesarios para acceder a un elemento.
###Un ndarray 1D tiene una dimensión.
####Ejemplo: array([1, 2, 3]).
###Un ndarray 2D tiene dos dimensiones.
####Ejemplo: array([[1, 2, 3], [4, 5, 6]]).
###Un ndarray 3D tiene tres dimensiones.
####Ejemplo: array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]).

###Forma (shape): Tupla que indica la longitud de cada dimensión. Se puede acceder a la forma de un ndarray mediante la propiedad .shape.
####Ejemplos:
  #### Un ndarray 1D con 5 elementos tiene forma (5,).
  #### Un ndarray 2D con 3

###Tamaño (size): Número total de elementos en el ndarray. Se puede acceder al tamaño de un ndarray mediante la propiedad .size.
#### Ejemplos:
  #### Un ndarray 1D con 5 elementos tiene un tamaño de 5.
  #### Un ndarray 2D  con 3  y 4 columnas tiene un tamaño de 12.
  #### Un ndarray 3D con 2 matrices de 3x4 tiene un tamaño de 24
  

In [ ]:
'''Indexación y selección de elementos: Se puede acceder a elementos específicos de un ndarray utilizando una secuencia deíndices entre corchetes.
Selección de elementos: Se pueden seleccionar subconjuntos de un ndarray utilizando diferentes técnicas como slicing, máscaras y boolean indexing'''
#Creación de un ndarray 2D
matriz_2 = [[1,2,3], [4,5,6], [7,8,9]]
matriz_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
#Acceso a un elemento físico (fila1, columna2)
matriz_2 [2][0]



7

###operaciones matriciales

In [ ]:
#Seleción de una fila (fila0)
fila = matriz_2 [2]
#columna = matriz_2 [[2],[1]]
#print(fila)
#print(columna)

#suma de los elementos del arreglo y muestra el resultado (45)
print(np.sum(matriz_2))
#fila

45


####Métodos para la Manipulación de ndarrays:
####NumPy proporciona una variedad de métodos paramanipular ndarrays de diferentes maneras. Algunos de estos métodos incluyen:
####reshape(): Permite cambiar la forma de un array sin cambiar sus datos.
####flatten(): Convierte un array multidimensional en un array unidimensional.
###transpose(): Permite cambiar el orden de las dimensiones de un array



In [ ]:
import numpy as np

#Creación de un ndarray 2D
matriz_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Array original:\n",matriz_3)

Array original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
reshaped_matriz3 = matriz_3.reshape((1,9))
print("Array Reshape: \n",  reshaped_matriz3)


Array Reshape: 
 [[1 2 3 4 5 6 7 8 9]]


In [ ]:
flattened_matriz3 = matriz_3.flatten()
print("Array flattten: \n", flattened_matriz3)


Array flattten: 
 [1 2 3 4 5 6 7 8 9]


In [ ]:
trasposed_matriz3 = matriz_3.transpose()
print("Array transpose: \n", trasposed_matriz3)


Array transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


####NumPy ofrece funciones para generar números aleatorios que son útiles en simulaciones, análisis de datos y otras aplicaciones. Algunas de estas funciones incluyen:

In [ ]:
#np.random.rand(): Genera números aleatorios entre 0 y 1 con una distribución uniforme
nume_aleat_uniformes = np.random.rand(5)
print("Números aleatorios uniformes: \n", nume_aleat_uniformes)
#nume_aleat_uniformes

Números aleatorios uniformes: 
 [0.01356795 0.84060747 0.67831681 0.94770502 0.58482999]


In [ ]:
#np.random.randint(): Genera números enteros aleatorios dentro de un rango especicado
numeros_aleatorios_enteros = np.random.randint(1,20,5)
print("Números aleatorios enteros: \n", numeros_aleatorios_enteros)

Números aleatorios enteros: 
 [13  9  1  5  3]


In [ ]:
#np.random.randn(): Genera números aleatorios con una distribución normal (gaussiana) con media 0 y desviación estándar 1.
numeros_aleatorios_normales = np.random.randn(5,5)
print("Números aleatorios normales: \n", numeros_aleatorios_normales)

Números aleatorios normales: 
 [[-0.5247769   0.12297335  0.05729345  2.07889584  1.98348831]
 [-0.72602521  0.16257308 -1.14826315 -1.09223331  1.87760025]
 [ 2.63592151  0.9839692   0.74092031  1.18385944 -0.39754083]
 [-0.0178241  -1.70474296  0.73211422 -1.24943258 -0.35619374]
 [-0.12914181  0.14962733  1.63660671 -0.53458383 -1.33947453]]


##Operaciones ariméticas



In [ ]:
# cada elemento del primer ndarray se combina con el correspondiente del segundo
suma1 = np.array([1, 2, 3])
suma2 = np.array([4, 5, 6])
print ("Salida: \n", suma1 + suma2)

Salida: 
 [5 7 9]


In [ ]:
#Multiplicación por una constante

print ("Salida suma1X5: \n", suma1 * 5)
print ("Salida suma2X5: \n", suma2 * 5)

Salida suma1X5: 
 [ 5 10 15]
Salida suma2X5: 
 [20 25 30]


In [ ]:
#Suma de matrices
suma3 = np.array([[1, 2],[3, 4], [5, 6]])
suma4 = np.array([[7, 8], [9, 10], [11, 12]])
print ("Salida suma3 + suma4: \n", suma3 + suma4)

Salida suma3 + suma4: 
 [[ 8 10]
 [12 14]
 [16 18]]


In [ ]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
array2 = np.array([10,11,12,13,14,15,16,17,18])
#print ("Salida array1 - array2: \n", array1 - array2)


In [ ]:
#Reshape:  permite cambiar la forma (dimensiones) de un ndarray sin cambiar sus datos. Es útil para transformar datos y prepararlos
#para su entrada en modelos de aprendizaje automático que pueden requerir formatos de entrada específicos
reshaped_array1 = array1.reshape(3,3)
reshaped_array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# reshape(): permite cambiar la forma (dimensiones) de un ndarray sin cambiar sus datos. Es útil para transformar datos y prepararlos
#para su entrada en modelos de aprendizaje automático que pueden requerir formatos de entrada específicos
reshaped_array2 = array2.reshape(3,3)
reshaped_array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
#sum(): Este método calcula la suma de los elementos a lo largo de un eje específico o de todo el ndarray
print("Resultado de la suma de matriz_3: \n", matriz_3.sum())

Resultado de la suma de matriz_3: 
 45


In [ ]:
#mean(): Calcula la media de los elementos a lo largo de un eje específico o de todo el ndarray
print("Resultado de la media de matriz_3: \n", reshaped_array2.mean())


Resultado de la media de matriz_3: 
 14.0


In [ ]:
#min() y max(): Estos métodos devuelven el valor mínimo y máximo del ndarray o a lo largo de un eje específico
print("Valor máximo de reshaped_array2: \n", reshaped_array2.max())
print("Valor mínimo de reshaped_array2: \n", reshaped_array2.min())



Valor máimo de reshaped_array2: 
 18
Valor mínimo de reshaped_array2: 
 10


In [ ]:
#argmin() y argmax(): Estos métodos devuelven los índices del valor mínimo y máximo, respectivamente.
print("Valor mínimo de reshaped_array2: \n", reshaped_array2.argmin())
print("Valor máximo de reshaped_array2: \n", reshaped_array2.argmax())


Valor mínimo de reshaped_array2: 
 0
Valor máximo de reshaped_array2: 
 8


In [ ]:
#std(): Calcula la desviación estándar de los elementos a lo largo de un eje específico o de todo el ndarray
print("Desviación estándar de reshaped_array1: \n", reshaped_array1.std())
#

Desviación estándar de reshaped_array1: 
 2.581988897471611


In [ ]:
#std(): Calcula la desviación estándar de los elementos a lo largo de un eje específico o de todo el ndarray
print("Desviación estándar de reshaped_array2: \n", reshaped_array2.std())

Desviación estándar de reshaped_array2: 
 2.581988897471611


##Desarrollo taller ejercicios con Numpy
Creacion de arrays

In [ ]:
#a. Crea un array unidimensional de longitud 5 con números enteros aleatorios
num_aleatorios_enteros = np.random.randint(1,20,5)
print("Números aleatorios enteros: \n", num_aleatorios_enteros)

Números aleatorios enteros: 
 [11 16 15  8 15]


In [ ]:
#b. Crea un array bidimensional de tamaño 3x3 con valores booleanos True
array_true = np.array([[True, True, True],
       [True, True, True],
       [True, True, True]])
array_true

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# c. Crea un array tridimensional de tamaño 3x2x4 con valores definidos
array1 = np.array ([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]],[[17, 18, 19, 20], [21, 22, 23, 24]]])
array1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
# c. Crea un array tridimensional de tamaño 2x3x4 con valores flotantes aleatorios
import numpy as np
g = np.random.rand(2,3,4)
g


array([[[0.77563682, 0.47304042, 0.76202532, 0.77391034],
        [0.26400004, 0.49515033, 0.86515106, 0.28355428],
        [0.726745  , 0.20664592, 0.57440972, 0.75683755]],

       [[0.83631854, 0.01304788, 0.02869463, 0.19712474],
        [0.62170724, 0.62606121, 0.63723218, 0.48359611],
        [0.11085499, 0.62297155, 0.87508284, 0.09856352]]])

##Acceso y Modificación de elementos

In [ ]:
#Accede al tercer elemento del array creado en el ejercicio 1a.
Acceder = num_aleatorios_enteros[2]
Acceder

15

In [ ]:
#b. Modifica el segundo elemento de la segunda fila del array creado en el ejercicio 1b para que sea false
Acceder2 = array_true[1,1] = False
array_true

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [ ]:
#Calcula la media de los elementos en la tercera dimensión del array creado en el ejercicio 1c.

calc_media = array1.mean()
calc_media


12.5

In [ ]:
calc_media2 = g.mean()
calc_media2

0.5045150929702636

##Operaciones aritméticas

In [ ]:
#a. Crea dos arrays unidimensionales de la misma longitud con números enteros aleatorios y realiza una suma elemento por elemento.
array_11 = np.random.randint(1, 50, 10)
array_22 = np.random.randint(1, 50, 10)
print ("Salida array_11: \n", array_11)
print ("Salida array_22: \n", array_22)
print ("Suma array_11 + array_22: \n", array_11 + array_22)


Salida array_11: 
 [46 25 36 37 45 25 39 23  5  5]
Salida array_22: 
 [11 22 38 45 17 40 26  2 35 44]
Suma array_1 + array_2: 
 [57 47 74 82 62 65 65 25 40 49]


In [ ]:
#b. Crea dos arrays bidimensionales de la misma forma y realiza una multiplicación matriz-vector.
matrix_1 = np.random.rand (2, 5)
matrix_2 = np.random.rand (2, 5)

print("Salida de matrix_1:\n", matrix_1)
print("Salida de matrix_2:\n", matrix_2)
print("Resultado de matrix_1 * matrix_2: \n", matrix_1 * matrix_2)



Salida de matrix_1:
 [[0.7738624  0.46799802 0.82432648 0.23239158 0.18650644]
 [0.21750721 0.18422029 0.92848386 0.40590444 0.39134725]]
Salida de matrix_2:
 [[0.55931758 0.49326055 0.89324602 0.02391081 0.43644967]
 [0.98526095 0.24466072 0.83912444 0.39707439 0.950426  ]]
Resultado de matrix_1 * matrix_2: 
 [[0.43283485 0.23084496 0.73632635 0.00555667 0.08140068]
 [0.21430136 0.04507147 0.7791135  0.16117426 0.3719466 ]]


In [ ]:
#c. Calcula el producto punto entre dos arrays tridimensionales de la misma forma

array_101 = np.random.randint(2, 100, (3, 3, 10))
array_102 = np.random.randint(1, 100, (3, 3, 10))

print("Salida de array_101:\n", array_101)
print("\nSalida de array_102:\n", array_102)
print("\nResultado de [array_101] * [array_102]: \n", array_101 * array_102)





Salida de array_101:
 [[[19  7 91 80 54 89 53 54 69 89]
  [ 8 84 44 93 45 52 70 49 45 31]
  [18 32 62 22 28 62 18 93 50 71]]

 [[20 10 31 30 94 27 33 51 66 13]
  [96 67 97 46 79 63 62 17 67 64]
  [77  7 10 83 28 71 14 17 56 80]]

 [[38 72 20 91 85 81 84 85 15 82]
  [96 23 13 20 38 91 57 23 57 70]
  [76 58 89 20 28 84 89 78  6 44]]]

Salida de array_102:
 [[[11 15 52  9 61 82 14 66 48 38]
  [41 74 70 79 13 10 95 48 76 72]
  [98 15 62 98 71 17 43  1 63 13]]

 [[ 3 84 11 55 26 10 16 78 47 85]
  [87 85  9 45  6 98 44 34 39 49]
  [52 72 50 75  4 64 70 64 24  7]]

 [[26 12 25 32 36  7 47 76 90 20]
  [34 16  9 76 27 62 31 29 54 68]
  [47 72 38 19 44 56 90 80 14 11]]]

Resultado de [array_101] * [array_102]: 
 [[[ 209  105 4732  720 3294 7298  742 3564 3312 3382]
  [ 328 6216 3080 7347  585  520 6650 2352 3420 2232]
  [1764  480 3844 2156 1988 1054  774   93 3150  923]]

 [[  60  840  341 1650 2444  270  528 3978 3102 1105]
  [8352 5695  873 2070  474 6174 2728  578 2613 3136]
  [4004  504  50

##Funciones y Métodos

In [ ]:
#a. Crea un array unidimensional con números enteros aleatorios y encuentra el valor máximo y mínimo
array_33 = np.random.randint(1, 100, 10)
array_33


array([13, 98, 79, 74, 67, 68, 58, 33, 35, 49])

In [ ]:
print("Valor máximo de array_33: \n", array_33.max())
print("Valor mínimo de array_33: \n", array_33.min())


Valor máximo de array_33: 
 98
Valor mínimo de array_33: 
 13


In [ ]:
#b. Crea un array bidimensional de tamaño 3x3 con valores flotantes y calcula la suma de cada columna
matrix_33 = np.random.rand(3,3)
matrix_34 = np.random.rand(3,3)
print("Salida de matrix_33:\n", matrix_33)
print("Salida de matrix_34:\n", matrix_34)
print ("El resultado de [Matrix_1] + [Matrix_2] es: \n", matrix_33 + matrix_34)


Salida de matrix_33:
 [[0.77644578 0.5538718  0.81110567]
 [0.82726591 0.84346154 0.10219096]
 [0.12736733 0.44600938 0.94927788]]
Salida de matrix_34:
 [[0.64962057 0.33972232 0.70301424]
 [0.92096979 0.91934587 0.01514865]
 [0.57823217 0.69256433 0.30106283]]
El resultado de [Matrix_1] + [Matrix_2] es: 
 [[1.42606635 0.89359412 1.51411991]
 [1.7482357  1.76280741 0.11733961]
 [0.70559949 1.13857371 1.25034071]]


In [ ]:
#c. Utiliza la función np.linspace() para crear un array unidimensional con 10 elementos equidistantes entre 0 y 1.
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

##Indexación y slicing

In [ ]:
#a. Crea un array unidimensional con números enteros del 0 al 9 y obtén los elementos pares
array_44 = np.arange(0,10)
array_44

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
elem_pares = array_44[array_44 % 2 == 0]
elem_pares

array([0, 2, 4, 6, 8])

In [ ]:
#b. Crea un array bidimensional de tamaño 4x4 y obtén la submatriz formada por las primeras 2 filas y las últimas 2 columnas
matrix_45 = np.random.randint(0, 100, (4, 4))
matrix_45


array([[35,  7, 64, 58],
       [ 3, 20, 82, 43],
       [ 9, 95, 45, 99],
       [99, 41, 99,  4]])

In [ ]:
submatriz = matrix_45[:2, 2:]
submatriz



array([[64, 58],
       [82, 43]])

In [ ]:
#c. Crea un array tridimensional de tamaño 3x3x3 y obtén el subarray formado por las primeras dos dimensiones
array_55 = np.random.randint(0, 100, (3, 3, 3))
array_55

array([[[77, 46, 81],
        [45, 91, 66],
        [22, 81,  0]],

       [[72, 22, 38],
        [86, 26, 22],
        [54,  1, 43]],

       [[88, 81, 58],
        [55, 73, 53],
        [42, 18, 56]]])

In [ ]:
subarray = array_55[:1, :2, :3]
subarray

array([[[77, 46, 81],
        [45, 91, 66]]])